name: DevCard

on:
  workflow_dispatch:
  push:
    branches:
      - main
  schedule:
    - cron: "0 */12 * * *" # At minute 0 past every 12th hour.

jobs:
  devcard:
    runs-on: ubuntu-latest
    steps:
      - name: devcard
        uses: dailydotdev/action-devcard@2.0.4
        with:
          devcard_id: be7ea40967ed430589a5ebf6de264277
